### ISSUE TITLE
ESM modules and module federation bug?

### ISSUE THREAD

**Issue by ebergama** [module-federation/module-federation-examples#1962] opened 2022-05-03 17:03 UTC
Hi everyone.

I'm working on adopting module federation on my project and I've found something I think it might be a potential bug.
I have one remote, one host application and one components library, the library is declared as ESM module via `"type": "module"` in the `package.json`, also both applications and the library consumes `styled-components` so I declare this dependency as shared.

The problem I'm facing is when I want to use the library in the host application via a regular import I see the transpiled webpack code does not access to the `default` property of `styled-components`, then it produces a runtime error like this:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/5274206/166502211-32297ec7-ffe4-4a1a-bec1-c2da3174485f.png">

Tho I've found the error is gone if:
a. I don't declare styled-components as shared (not ideal)
b. I don't declare my library as `"type": "module"`

I've used the basic-example to mimic the scenario I have on my project, you can will find both app1 and app2 plus my `esm-package` with a very simple styled component.
Also you can appreciate I've commented the "federated" portion of `app1` given that the the error is exclusive of the bundle generated for `app1`

Any thoughts?

https://github.com/ebergama/module-federation-bug

**Comment by ScriptedAlchemy** [comment] 2022-05-09 05:51
will have to look into this. Ive not tried ESM with MF - but it should work if the normal webpack build works

**Comment by ebergama** [comment] 2022-05-09 17:44
@ScriptedAlchemy Thanks for replying, if you install the repo I shared and run it you should be able to reproduce the exact issue I mention

**Comment by ScriptedAlchemy** [comment] 2022-06-28 07:35
Okay so this isn’t actually a bug. If I build ESM packages for webpack I’ll get the same issue. The problem is you are not specifying the module type correctly. 

If it’s npm, it’s usually because type isn’t set to module or it’s not a stateless module. If it’s MF then you probbbaly need to set remoteType. 

Webpack creates a proxy export object that re-exports whatever you import, ESM has to be evaluated upfront unlike requrie, which is evaluated just in time. So this usually shows up when webpack is trying to import it just in time instead of treating it like ESM and resolving dependency bindings upfront. 

Not a bug, a misconfiguration of module types in your build

**Closed as completed by ScriptedAlchemy** 2022-06-28 07:35 UTC
Labels: good first issue, help wanted, Implementation Detail

**Comment by vyachsed** [comment] 2022-10-04 13:39
+1
the same issue
@ScriptedAlchemy please check

**Comment by ScriptedAlchemy** [comment] 2022-10-05 03:04
This works. I've tested it. Configure it properly

**Comment by PIMBA** [comment] 2023-09-13 07:42
Same issue, fixed by removing `"type": "module"`.
